### ISSUE TITLE
Harder craft for the tracker compass

### ISSUE THREAD

**Issue by AmauryCarrade** [zDevelopers/UHPlugin#34]
The current craft for the compass is potentially too simple.

![Current craft](http://amaury.carrade.eu/files/Minecraft/Plugins/UH/UHPlugin_Craft_Compass.png)

Idea: add an option (`harderCraft`) to replace the redstone with an ender pearl.

``` yaml
compass: 
    enabled: true
    harderCraft: true # craft with an ender pearl instead of a redstone powder.
```

Niark.
