### ISSUE TITLE
The three different compasses in the same game

### ISSUE THREAD

**Issue by AmauryCarrade** [zDevelopers/UHPlugin#39]
(As an option.)

In a game, **all** the compass recipes are available, but:
- the one with redstone is an inaccurate one, pointing very approximately to the nearest player, and sometimes to a random player (team included?);
- the one with an ender pearl point the nearest player, just like the current behaviour of the compass;
- the one with an eye of ender points the nearest player, give his name and the approximate distance (or precise distance?).

``` yml
compass:
    enabled: true
    enableMultipleCompasses: true
    logCompassUsage: true

    # Options if multiple compasses is disabled
    oneCompass:
        recipe: "medium"  # just like before

    # Options if multiple compasses is enabled
    multipleCompasses:
        enabledRecipes:
            easy: true
            medium: true
            hard: true

        inaccurateCompass:  # easy recipe
            pointsToRandomPlayer: 
                # If non-zero, the compass will have a probability to point to a random player instead of the nearest one.
                probability: 0.2  # 0 = never, 1 = always.
            pointingError:
                maxDistance: 100  # in blocks, the maximal distance between the real one and the bad one.

        preciseCompass:  # hard recipe
            # If true, distance given in blocks.
            # Else, "very close", "close" or "far"
            preciseDistance: false

            # Displays the name of the nearest player.
            # Can be used to get the health of this player (in the player list, if enabled).
            giveName: true

            # "in the ground" or "on the surface"
            givePosition: false

            # Allows users with this compass to track the nearest players, during a small time;
            # this costs some emeralds.
            # Right-click = normal use (points to the nearest player, consumes a rotten flesh).
            # Left-click = menu between these three options (points to, track for a small time, for a long time).
            track:
                updateInterval: 4  # in seconds, the interval between the update of the tracking compasses.
                smallTime:
                    enabled: true
                    duration: 30  # seconds
                    cost: 1  # emeralds
                longTime:
                    enabled: true
                    duration: 180  # seconds
                    cost: 4  # emeralds
```

_An idea by my sister (neither on GitHub nor on BukkitDev)._
