### ISSUE TITLE
Add a way to execute a command when the game ends.

### ISSUE THREAD

**Issue by AmauryCarrade** [zDevelopers/UHPlugin#50]
Configurable delay.

Example of configuration:

``` yml
finish:
    # [...]
    commands:
        execute-start:
           - exec: uh border warning 500
             delay: 40m
        execute-end:
           - exec: reload
             delay: 0
```

Edit: final config below.

``` yml
# Execute commands during the game or after the end of it, and after a configurable delay?
# Format explained below.
# Respect the spaces before the keywords ("exec" and "delay" need to be aligned).
commands:
    # Commands executed after the beginning of the game.
    # (The moment when /uh start or /uh start slow go is executed.)
    execute-start:
      #- exec: command args
      #  delay: "40:00" (format: "mm", "mm:ss" or "hh:mm:ss". If invalid or not present, 0 seconds.)
      -
    # Commands executed after the end of the game.
    # (After the last kill, when only one team is left.)
    execute-end:
      -
```
