### ISSUE TITLE
Horrible laggs while playings - Click for more information

### ISSUE THREAD

**Issue by Amauryroco** [zDevelopers/UHPlugin#60]
Hello !

I tested this amazing plugin with my friends, and when we started it, the time was moving 3 seconds by 3 seconds (ex: 15:30, 15:27, 15:24) and we could only hit mobs every 2 seconds or so. But when we broke blocs, they don't lagg and drop as usual. The only lagg were when hitting a mob and the Timer Disfunction Problem , AKA: TDP (I just invented the name, but the laggs are real). It "lagged" for about 1h30min and then it stopped. Unfortunately there was a fight before it stopped lagging, and I quote from the spectators: "They were circling around each other trying to hit the other player. They took damage every 2 seconds but there movements were not lagging". And when the fight was over, 5 or 10 minutes after it stopped (or maybe just after the fight). It wasn't just my computer or my internet, it was the plugin or the server who lagged, but I don't suspect it was the server, because I rent it at omgserv (http://www.omgserv.com/fr/offres/serveur-minecraft/illimite/). I rented servers from omgserv for 2 years now, and they are a real good quality, because it didn't lagg when we were playing UHC/KTP with the original KTP plugin by azenet 4 months ago (even if azenet codes plugin with his feets).

So I am going to tell you EXACTLY what I did to prepare this UHC so that maybe you could help me solve the problem.

I looked for a map on the application AMIDST. I found one. I thought we were going to be 20 players but finally we were 12 or less, I don't remember exactly. I prepared it to be a solo. I made the spawn at 0 154 0, and then I installed the plugin UHC Reloaded 1.1.3 Snapshot. My configurations were:

```
# 
# ## Welcome in the UltraHardcore Reloaded configuration file ##
# 
# 
# About the "sound" configuration, the format is always the same:
# sound:
#     name:   The name of the sound. Names: see http://l.carrade.eu/bukkit-sounds . Set to "NONE" to disable.
#     volume: The volume of the sound. 1 is the normal volume. You can use a decimal value.
#     pitch:  The pitch of the sound.  1 is the normal pitch.  You can use a decimal value.
# 


# Available languages: en_US, fr_FR, pt_PT.
lang: fr_FR



episodes:
    enabled: true

    # Format: "mm", "mm:ss" or "hh:mm:ss". If invalid, 20 minutes.
    # Don't remove the "quotes" (because of the commas)!
    length: "20:00"



map:
    size: 2000
    circular: false
    wall:
        height: 128
        block:
            # The replaceAir block will be placed where there where some transparent blocks or trees before.
            # The replaceSolid one, where there was an other kind of block.
            replaceAir: BEDROCK
            replaceSolid: BEDROCK
    border:
        # The delay between two warning messages sent to the players out of a future border 
        # (this warning is set using /uh border warning <futureDiameter>).
        warningInterval: 90  # seconds

    spawnPoints:
        # Don't generate the spawn points (with /uh spawns generate) above the water?
        dontGenerateAboveWater: true



daylightCycle:
    do: false
    time: 6000  # Initial time (or game time if the daylight cycle is disabled) in ticks. 6000 = noon.



scoreboard:
    title: §7Kill §8the §4Blitzcrew

    # Scoreboard displayed on the left of the screen
    enabled: true
    episode: true
    players: true
    teams: true
    timer: true
    freezeStatus: true

    # Health in the list of the players
    health: true



# Teleport the players to the spawn point on login if the game is not started?
# Avoids the random spawn point of Minecraft, and teleports them back to
# there if they log out then in.
teleportToSpawnIfNotStarted: true



start:
    slow:
        delayBetweenTP: 2  # in seconds

    sound:
        name: NONE
        volume: 1
        pitch: 1



death:
    messages:
        notifyIfTeamHasFallen: true
        deathMessagesFormat: "§6"  # Use this to increase visibility of death messages.
        teamDeathMessagesFormat: "§6"

    kick:
        do: true
        time: 30
        allow-reconnect: true

    head:
        drop: true
        pvpOnly: false

    give-xp-to-killer:
        levels: 0  # set to 0 to disable
        onlyOtherTeam: true  # Give XP only if the player kills a player from another team?

    announcements:
        lightning-strike: false

        sound:
            name: WITHER_SPAWN
            volume: 10000
            pitch: 1



# If true, the name of the players will be colorized according to the teams.
colorizeChat: true



gameplay-changes:
    weather: true  # If false, the "bad" weather (rain, thunder) is disabled.

    replaceGhastTearsWithGold: true
    craftGoldenMelonWithGoldBlock: true

    craftGoldenAppleFromHead:
        fromHuman:
            do: true
            numberCrafted: 1
            addLore: true
            craftNotchApple: false
        fromWither:
            do: true
            numberCrafted: 4
            addLore: true
            craftNotchApple: false

    goldenApple:
        regeneration:
            # Half-hearts regenerated by one apple. Vanilla: normal 4, notch 180 (yes, 180).
            normal: 4
            notch: 180
            fromNormalHead: 6
            fromNotchHead: 180

        disableNotchApples: true

    disableEnderpearlsDamages: false

    disableLevelIIPotions: true

    witch:
        disableNaturalSpawn: true
        disableLightningSpawn: false  # from a villager


    # If true a compass will show the nearest player, and the craft will be different.
    # Else, the craft will be standard and the compass will show the spawn point of the team/player (not the world spawn point).
    compass:
        enabled: true

        # The special recipe is with an ingredient in the center, and then,
        # from the top, clockwise: iron, spider eye, iron, rotten flesh, iron, bone, iron, gunpowder.
        # This field change the central ingredient.
        # "easy": redstone (like the normal compass).
        # "medium": ender pearl.
        # "hard": eye of ender.
        recipe: "easy"



teams-options:
    canSeeFriendlyInvisibles: true
    allowFriendlyFire: true

    #0 = unlimited.
    maxPlayersPerTeam: 0



hardcore-hearts:
    # Display hardcore hearts instead of normal ones?
    display: false

    # If a player die, his client will display an hardcore Game Over screen, without a « Respawn » button.
    # But the player CAN respawn, by clicking « Leave server » and then, on the confirmation screen,
    # « Respawn ».
    # With this option enabled, a short message will notify the player about that.
    # Notice: this will be disabled even with this set to true if the hardcore hearts are not enabled (useless).
    respawnMessage: false



# Automatically respawn the player after his death.
# Avoid the interrogation about the ability to respawn, if hardcore hearts are enabled.
auto-respawn:
    do: true
    delay: 6  # seconds



# Controls the behavior of the /uh finish command
finish:
    auto:
        do: true  # Execute /uh finish automatically a few seconds after the final death?
        timeAfterLastDeath: 3  # The command will be executed this amount of seconds after the last death.

    message: true  # If true, the name of the winner(s) will be broadcasted.
    fireworks:
        enabled: true  # If true, some fireworks will be launched at the location of the winners.
        duration: 20   # In seconds.
        areaSize: 6    # The size of the square, centered on each player, where the fireworks will be launched.



dynmap:
    showSpawnLocations: true
    showDeathLocations: true



# Log the private team-chat in the console?
logTeamChat: false



protips:
    sound:
        name: NOTE_PLING
        volume: 2
        pitch: 3

    teamchat:
        useTCommand: true  # Protip: team-chat command
        lock: true         # Protip: can lock the team-chat
        useGCommand: true  # Protip: global-chat command

    crafts:
        goldenHead: true        # ProTip: craft of golden apples with an head
        compassEasy: true       # Protip: "easy" compass craft
        compassMedium: true     # Protip: "medium" compass craft
        compassHard: true       # Protip: "hard" compass craft
        glisteringMelon: true   # Protip: glistering melon crafted with a gold block
        noEnchGoldenApple: true # Protip: enchanted golden apple disabled

    start:
        invincibility: true  # Protip: 30 seconds (25 after the message) of invincibility.



# Use this to set the spawnpoints of the teams (or the players)
# You can also use the command `/uh spawns add` to add temporary spawn points,
# and `/uh spawns generate` to automatically generate them. (See `/uh spawns` for documentation.)
# (The spawn points added through `/uh spawns` are deleted when the server is stopped.)
#
# Format:
#     - x,z
#     - x,z
#     - etc.

spawnpoints:
    - 25,25
    - and a bunch of other spawnpoints (Exaclty 18 in total)



# Use this to pre-register the teams.
# Format:
#     - color
#  -- OR --
#     - color,name

teams:
    -
```

There were 18 spawnpoints in a map of 2000x2000. I deleted a spawnpoint before it started and put it 100 blocs away from the previous coordinates. After configuring this (before I did the spawnpoint thing) I did /rl . Then I did /wb fill, then waited 50 MINUTES for it to complete. Then I did /uh generatewalls. After that I waited 2 days or maybe less with the server opened, and with the automatic reboot off. We built a redstone circuit a the spawn with the plugin on, a minecart rollercoaster (a little one) and embellished the spawn. We even put an end portal (not the blocs to do it, just the bloc of the end portal. (we didn't use that: http://minecraft.gamepedia.com/End_Portal_(block) , but only the portal thing)). Then I started the game by doing /uh start. It was already "lagging" when a guy just suicided because we couldn't Skype with him (don't judge. I know he's stupid, that's why I won't invite again). And that's about it.

I don't know what I did wrong and I searched but there is so many possibilities. Do you think it was because I did the config wrong ? I think you guys know the plugin better than I do, so if I did something wrong about the config, tell me ! =D

Sorry for the long issue D=
