### ISSUE TITLE
Deny PvP in first Episode

### ISSUE THREAD

**Issue by YoLaw** [zDevelopers/UHPlugin#88]
Hello! :)
I have another idea wich is in my opinion easy to release...
Can you add an option to deny PvP in the first Episode please? :)
Thanks :)

**Comment by AmauryCarrade** [comment]
Will be added, in the 1.4 because the features of the 1.2 are frozen (released soon).

Either after x episodes or x hours/minutes/seconds.

**Comment by YoLaw** [comment]
Super! :)

**Comment by pilax** [comment]
Salut à toi,

Tout d'abord, merci pour ce merveilleux plugins et les mises à jours que tu lui apportes !
Il y a enormément évolué depuis la version de base de Aznet et devient très complet :)

Effectiement il manque pour le moment (1.2) la possibilité de pouvoir retirer le pvp pendant un certains temps, mais c'est une bonne chose de savoir que cela va être intégré à la 1.4 (d'ailleurs qu'en est-il de la 1.3 ? pas de release ?!).

La 1.4 n'étant pas pour demain, et je peux le comprendre vu le contenu/modifications que tu vas lui apporter, il y a t-il une possibilité/solution temporaire avec la version actuelle (1.2) de mettre en place un anti pvp pendant un certains temps ? 
J'ai fais un test via PvPTimer mais non concluant, je m'en doutais par avance, mais qui ne tente rien n'a rien ^^.

Peut être as tu une solution magique, ou dans le cas contraire je patienterais comme tout le monde la version 1.4 :)

Merci encore et bon courage pour la suite du dev.

Pilax

**Comment by AmauryCarrade** [comment]
C'est assez simple à mettre en place dés maintenant avec la version 1.2, grâce à la puissance de l'exécuteur de commandes inclu avec, que j'ai justement ajouté pour inclure ce genre de possibilités.
D'ailleurs, vue la possibilité, je vais peut-être ne pas implémenter ceci directement, pour plutôt faire une FAQ expliquant comment le faire tel que précisé plus bas.

Donc, si vous ne le savez pas (encore très peu documenté... il faudra que je le fasse), il y a dans le plugin (c'est [dans la config](https://github.com/AmauryCarrade/UHPlugin/blob/dev/src/main/resources/config.yml#L291-L310)) un moyen d'exécuter des commandes arbitraires après un délai quelconque après le chargement du serveur, le début du jeu ou sa fin.

Donc, si vous avez un plugin qui permet d'activer le PVP avec `/pvp on` et de le désactiver avec `/pvp off` (par exemple, à adapter selon le plugin), il suffit de faire ceci dans le fichier `config.yml` : 
```yml
# Execute commands during the game or after the end of it, and after a configurable delay?
# Format explained below.
# Respect the spaces before the keywords ("exec" and "delay" need to be aligned).
commands:
    # Commands executed when the server starts.
    # These commands are also executed when the server is reloaded.
    execute-server-start:
     #- exec: command args
     # delay: "40:00" (format: "mm", "mm:ss" or "hh:mm:ss". If invalid or not present, 0 seconds.)
      - exec: "pvp off"
    # Commands executed after the beginning of the game.
    # (The moment when /uh start or /uh start slow go is executed.)
    execute-start:
      - exec: "pvp on"
        delay: "20:00"  # par exemple
     # Affichage (on peut faire ce qu'on veut après, ici je met titre et message dans le chat
      - exec: "tellraw @a {'text':'Le PVP est désormais actif !','color':'red','bold':'true'}"
        delay: "20:00"
      - exec: "title @a title '§4§lATTENTION'"
        delay: "20:00"
      - exec: "title @a subtitle '§cLe PVP est désormais actif'"
        delay: "20:00"
```

J'ai trouvé pas mal de plugins pour gérer le PVP, notamment [PVP Switcher](http://dev.bukkit.org/bukkit-plugins/pvpswitcher/) (commandes `/pvpswitch on` et `/pvpswitch off` ; il faut enregistrer dans la config ou avec une commande les mondes dans lesquels le PVP est touché par contre, cf. la page de BukkitDev)). Je ne l'ai pas testé.  

  

> (d'ailleurs qu'en est-il de la 1.3 ? pas de release ?!).

Je versionne à-là-Linux (ou Gnome) : `1.<nombre pair>` = version stable, et `1.<nombre impair>` = version de développement.
En soi la version 1.3 existe actuellement, il s'agit [de la version instable sur la branche `dev`](https://github.com/AmauryCarrade/UHPlugin/blob/dev/src/main/resources/plugin.yml#L4).


-----

*English version: @pilax asked on how to deny PVP in the beginning of the game with the current 1.2 version. I suggested the use of the commands executor built-in, with a plugin to enable/disable the PVP using a command*
